apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- if .Values.monitoring.enabled }}
  PROMETHEUS_URL: "http://{{ .Release.Name }}-monitoring-prometheus:9090"
  {{- else }}
  PROMETHEUS_URL: {{ .Values.prometheus.url | quote }}
  {{- end }}
  SQLALCHEMY_DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  K8S_MODE: "incluster"
  CORS_ORIGINS: "*"
  JWT_ALGORITHM: "HS256"

  CLUSTER_NAME: {{ .Values.clusterName | default "in-cluster" | quote }}

