apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" .Release.Name) }}
  
  {{- if and $secret (not .Values.api.jwtSecret) (hasKey $secret.data "JWT_SECRET") }}
  JWT_SECRET: {{ index $secret.data "JWT_SECRET" }}
  {{- else }}
  JWT_SECRET: {{ (default (randAlphaNum 32) .Values.api.jwtSecret) | b64enc | quote }}
  {{- end }}

  {{- if and $secret (not .Values.api.adminPassword) (hasKey $secret.data "ADMIN_PASSWORD") }}
  ADMIN_PASSWORD: {{ index $secret.data "ADMIN_PASSWORD" }}
  {{- else }}
  ADMIN_PASSWORD: {{ (default (randAlphaNum 16) .Values.api.adminPassword) | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- end }}
