apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  JWT_SECRET: {{ (default (randAlphaNum 32) .Values.api.jwtSecret) | b64enc | quote }}
  ADMIN_PASSWORD: {{ (default (randAlphaNum 16) .Values.api.adminPassword) | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- end }}
