---
apiVersion: v2
name: metrics
description: A cloud-inspired monitoring dashboard with Prometheus alerts, user activity auditing, and live cluster visibility
type: application
version: "1.0.2"
appVersion: "1.1.7"

dependencies:
  - name: kube-prometheus-stack
    version: "72.x"
    repository: https://prometheus-community.github.io/helm-charts
    alias: monitoring
    condition: monitoring.enabled
  - name: postgresql
    version: "*"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
